### ISSUE TITLE
module declares its path as: greedy but was required as: github.com/skuzzymiglet/greedy

### ISSUE THREAD

**Issue by jtorvald** [skuzzymiglet/greedy#1]
$ go get -u github.com/skuzzymiglet/greedy 
go: downloading github.com/skuzzymiglet/greedy v0.0.0-20201101214333-f5111c20ff90
go: github.com/skuzzymiglet/greedy upgrade => v0.0.0-20201101214333-f5111c20ff90
go get: github.com/skuzzymiglet/greedy@v0.0.0-20201101214333-f5111c20ff90: parsing go.mod:
	module declares its path as: greedy
	        but was required as: github.com/skuzzymiglet/greedy

**Comment by skuzzymiglet** [comment]
Thanks so much for reporting this!

**Comment by skuzzymiglet** [comment]
Hey @jtorvald, mind me asking how it was using greedy?

**Comment by jtorvald** [comment]
@skuzzymiglet hi! thanks for bringing it to my attention again. It takes a bit to get used to it but I guess it works. I will use it a bit more from now on to see if it benefits me.
What I'm missing is a legend of the keys somewhere. I tried to CTRL+C out of it but couldn't. Then I found that there are a couple of keys to use on the github page.
Also: how do I reset  the position to zero for a URL when I already read it?

Everytime I start it with the same URL I see this and the program exits:
2020/12/07 21:48:15 Resuming at word 287
2020/12/07 21:48:15 Saving position...

**Comment by skuzzymiglet** [comment]
I've just fixed that in a658c28120c50dfeacce9fd5614a537b52c36b55. If you `go get -u -v` again, it'll get the fixed version.

I may add Ctrl-C (it's a TODO rn). I could also add an in-program key legend but that would be visually cluttering.

I have the shortcut Windows-R configured in DWM, which runs `xclip -o -sel primary | greedy -w 500`. Primary selection so I don't have to Ctrl-C the text, just select it. Pretty convenient for me.

Thanks for the feedback.
